### ISSUE TITLE
How do I scratch train or fine tune?

### ISSUE THREAD

**Issue by ChangGiMoon** [Howardkhh/MVATeam1#1]
Thanks for the good research. I'm trying to fine-tune my custom data using pre-trained weights. Is there code?

**Comment by Howardkhh** [comment]
Please use [tools/train.py](https://github.com/Howardkhh/MVATeam1/blob/main/tools/train.py) for training. More details can be found in the [MMDetection documentation](https://mmdetection.readthedocs.io/en/v2.24.1/1_exist_data_model.html).
